import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import RootLayout from "@/layouts/root";

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Vebos-media",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <RootLayout> {children}</RootLayout>
      </body>
    </html>
  );
}
